### PR TITLE
Install an R kernel by default!

### PR DESCRIPTION
**Pull request by rgbkrk**
Installs an R kernel, as well as a few extra packages:
- ggplot2
- Hmisc
- plyr
- randomForest
- RColorBrewer
- reshape
- reshape2
- stringr
- XML

The installed packages came from me looking at top packages and knowing which I've used in my old decaying mathematical past.

/cc @takluyver for his R background and, well, he wrote the R kernel!

### CODE REVIEW

**Comment by stonebig** [comment]
Hi,

Comming back to this. To test issues on Ipython + Rmagic, it would be nice to have "dplyr" +"nycflights13"

see https://bitbucket.org/rpy2/rpy2/issue/253/r-select-flights-year-day

**Comment by rgbkrk** [comment]
Now that the demo image has been moved into its own repository, we should discuss packages here: https://github.com/jupyter/docker-demo-images

We currently have [dplyr installed](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile#L59) and I would be open to a change that includes nycflights13 since it appears to be a common example used with rpy2.

**Comment by stonebig** [comment]
Sorry I'm not sure I understand what you mean about `dplyr installed`.
If I try `library("dplyr")` in tmpnb.org on a R kernel, I have an error.

tmpnb_r_dplyr

**Comment by stonebig** [comment]
`installed.packages()`
shows "only" 
````
             Package        LibPath                   Version    Priority     
acepack      "acepack"      "/home/jovyan/.R"         "1.3-3.3"  NA           
assertthat   "assertthat"   "/home/jovyan/.R"         "0.1"      NA           
base64       "base64"       "/home/jovyan/.R"         "1.1"      NA           
BH           "BH"           "/home/jovyan/.R"         "1.55.0-3" NA           
brew         "brew"         "/home/jovyan/.R"         "1.0-6"    NA           
colorspace   "colorspace"   "/home/jovyan/.R"         "1.2-4"    NA           
DBI          "DBI"          "/home/jovyan/.R"         "0.3.1"    NA           
devtools     "devtools"     "/home/jovyan/.R"         "1.7.0"    NA           
dichromat    "dichromat"    "/home/jovyan/.R"         "2.0-0"    NA           
digest       "digest"       "/home/jovyan/.R"         "0.6.8"    NA           
evaluate     "evaluate"     "/home/jovyan/.R"         "0.5.5"    NA           
Formula      "Formula"      "/home/jovyan/.R"         "1.2-0"    NA           
ggplot2      "ggplot2"      "/home/jovyan/.R"         "1.0.0"    NA           
gtable       "gtable"       "/home/jovyan/.R"         "0.1.2"    NA           
Hmisc        "Hmisc"        "/home/jovyan/.R"         "3.14-6"   NA           
httr         "httr"         "/home/jovyan/.R"         "0.6.1"    NA           
IRdisplay    "IRdisplay"    "/home/jovyan/.R"         "0.1"      NA           
IRkernel     "IRkernel"     "/home/jovyan/.R"         "0.1"      NA           
jsonlite     "jsonlite"     "/home/jovyan/.R"         "0.9.14"   NA           
labeling     "labeling"     "/home/jovyan/.R"         "0.3"      NA           
latticeExtra "latticeExtra" "/home/jovyan/.R"         "0.6-26"   NA           
magrittr     "magrittr"     "/home/jovyan/.R"         "1.5"      NA           
memoise      "memoise"      "/home/jovyan/.R"         "0.2.1"    NA           
mime         "mime"         "/home/jovyan/.R"         "0.2"      NA           
munsell      "munsell"      "/home/jovyan/.R"         "0.4.2"    NA           
plyr         "plyr"         "/home/jovyan/.R"         "1.8.1"    NA           
proto        "proto"        "/home/jovyan/.R"         "0.3-10"   NA           
R6           "R6"           "/home/jovyan/.R"         "2.0.1"    NA           
randomForest "randomForest" "/home/jovyan/.R"         "4.6-10"   NA           
RColorBrewer "RColorBrewer" "/home/jovyan/.R"         "1.1-2"    NA           
Rcpp         "Rcpp"         "/home/jovyan/.R"         "0.11.4"   NA           
RCurl        "RCurl"        "/home/jovyan/.R"         "1.95-4.5" NA           
reshape      "reshape"      "/home/jovyan/.R"         "0.8.5"    NA           
reshape2     "reshape2"     "/home/jovyan/.R"         "1.4.1"    NA           
roxygen2     "roxygen2"     "/home/jovyan/.R"         "4.1.0"    NA           
rstudioapi   "rstudioapi"   "/home/jovyan/.R"         "0.2"      NA           
rzmq         "rzmq"         "/home/jovyan/.R"         "0.7.7"    NA           
scales       "scales"       "/home/jovyan/.R"         "0.2.4"    NA           
stringr      "stringr"      "/home/jovyan/.R"         "0.6.2"    NA           
uuid         "uuid"         "/home/jovyan/.R"         "0.1-1"    NA           
whisker      "whisker"      "/home/jovyan/.R"         "0.3-2"    NA           
XML          "XML"          "/home/jovyan/.R"         "3.98-1.1" NA           
bitops       "bitops"       "/usr/lib/R/site-library" "1.0-6"    NA           
RCurl        "RCurl"        "/usr/lib/R/site-library" "1.95-4.1" NA           
base         "base"         "/usr/lib/R/library"      "3.0.2"    "base"       
boot         "boot"         "/usr/lib/R/library"      "1.3-9"    "recommended"
class        "class"        "/usr/lib/R/library"      "7.3-9"    "recommended"
cluster      "cluster"      "/usr/lib/R/library"      "1.14.4"   "recommended"
codetools    "codetools"    "/usr/lib/R/library"      "0.2-8"    "recommended"
compiler     "compiler"     "/usr/lib/R/library"      "3.0.2"    "base"       
datasets     "datasets"     "/usr/lib/R/library"      "3.0.2"    "base"       
foreign      "foreign"      "/usr/lib/R/library"      "0.8-59"   "recommended"
graphics     "graphics"     "/usr/lib/R/library"      "3.0.2"    "base"       
grDevices    "grDevices"    "/usr/lib/R/library"      "3.0.2"    "base"       
grid         "grid"         "/usr/lib/R/library"      "3.0.2"    "base"       
KernSmooth   "KernSmooth"   "/usr/lib/R/library"      "2.23-10"  "recommended"
lattice      "lattice"      "/usr/lib/R/library"      "0.20-24"  "recommended"
MASS         "MASS"         "/usr/lib/R/library"      "7.3-29"   "recommended"
Matrix       "Matrix"       "/usr/lib/R/library"      "1.1-2"    "recommended"
methods      "methods"      "/usr/lib/R/library"      "3.0.2"    "base"       
mgcv         "mgcv"         "/usr/lib/R/library"      "1.7-28"   "recommended"
nlme         "nlme"         "/usr/lib/R/library"      "3.1-113"  "recommended"
nnet         "nnet"         "/usr/lib/R/library"      "7.3-7"    "recommended"
parallel     "parallel"     "/usr/lib/R/library"      "3.0.2"    "base"       
rpart        "rpart"        "/usr/lib/R/library"      "4.1-5"    "recommended"
spatial      "spatial"      "/usr/lib/R/library"      "7.3-7"    "recommended"
splines      "splines"      "/usr/lib/R/library"      "3.0.2"    "base"       
stats        "stats"        "/usr/lib/R/library"      "3.0.2"    "base"       
stats4       "stats4"       "/usr/lib/R/library"      "3.0.2"    "base"       
survival     "survival"     "/usr/lib/R/library"      "2.37-7"   "recommended"
tcltk        "tcltk"        "/usr/lib/R/library"      "3.0.2"    "base"       
tools        "tools"        "/usr/lib/R/library"      "3.0.2"    "base"       
utils        "utils"        "/usr/lib/R/library"      "3.0.2"    "base"       
             Depends                                                
acepack      NA                                                     
assertthat   NA                                                     
base64       NA                                                     
BH           NA                                                     
brew         NA                                                     
colorspace   "R (>= 2.13.0), methods"                               
DBI          "R (>= 2.15.0), methods"                               
devtools     "R (>= 3.0.2)"                                         
dichromat    "R (>= 2.10), stats"                                   
digest       "R (>= 2.4.1)"                                         
evaluate     "R (>= 2.14.0)"                                        
Formula      "R (>= 2.0.0), stats"                                  
ggplot2      "R (>= 2.14), stats, methods"                          
gtable       "R (>= 2.14), grid"                                    
Hmisc        "methods, grid, lattice, survival (>= 2.37-6), Formula"
httr         "R (>= 3.0.0)"                                         
IRdisplay    "\nR (>= 3.0.1)"                                       
IRkernel     "\nR (>= 3.0.1)"                                       
jsonlite     "methods"                                              
labeling     NA                                                     
latticeExtra "R (>= 2.10.0), RColorBrewer, lattice (>= 0.18-1)"     
magrittr     NA                                                     
memoise      NA                                                     
mime         NA                                                     
munsell      NA                                                     
plyr         "R (>= 2.11.0)"                                        
proto        NA                                                     
R6           "R (>= 3.0)"                                           
randomForest "R (>= 2.5.0), stats"                                  
RColorBrewer "R (>= 2.0.0)"                                         
Rcpp         "R (>= 3.0.0)"                                         
RCurl        "R (>= 3.0.0), methods, bitops"                        
reshape      "R (>= 2.6.1)"                                         
reshape2     NA                                                     
roxygen2     "R (>= 3.0.2)"                                         
rstudioapi   NA                                                     
rzmq         NA                                                     
scales       "R (>= 2.13)"                                          
stringr      "R (>= 2.14)"                                          
uuid         "R (>= 2.9.0)"                                         
whisker      NA                                                     
XML          "R (>= 1.2.0), methods, utils"                         
bitops       NA                                                     
RCurl        "R (>= 2.7.0), methods, bitops"                        
base         NA                                                     
boot         "R (>= 3.0.0), graphics, stats"                        
class        "R (>= 3.0.0), stats, utils"                           
cluster      "R (>= 2.10.0), stats, graphics, utils"                
codetools    "R (>= 2.1)"                                           
compiler     NA                                                     
datasets     NA                                                     
foreign      "R (>= 3.0.0), stats"                                  
graphics     NA                                                     
grDevices    NA                                                     
grid         NA                                                     
KernSmooth   "R (>= 2.5.0), stats"                                  
lattice      "R (>= 2.15.1)"                                        
MASS         "R (>= 3.0.0), grDevices, graphics, stats, utils"      
Matrix       "R (>= 2.15.2), methods"                               
methods      NA                                                     
mgcv         "R (>= 2.14.0), nlme (>= 3.1-64)"                      
nlme         "graphics, stats, R (>= 3.0.0)"                        
nnet         "R (>= 2.14.0), stats, utils"                          
parallel     NA                                                     
rpart        "R (>= 2.15.0), graphics, stats, grDevices"            
spatial      "R (>= 3.0.0), graphics, stats, utils"                 
splines      NA                                                     
stats        NA                                                     
stats4       "methods, graphics, stats"                             
survival     "stats, utils, graphics, splines, R (>= 2.13.0)"       
tcltk        NA                                                     
tools        NA                                                     
utils        NA                                                     
````

**Comment by rgbkrk** [comment]
Am I [installing dplyr](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile#L59) incorrectly?

**Comment by rgbkrk** [comment]
`install.packages('dplyr')`

**Comment by stonebig** [comment]
Well It's not written like that in your code.
Maybe should you do it one module at a time  ?
like 
````
install.packages("tidyr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("R.utils")
install.packages("zoo")
install.packages("forecast")
install.packages("nycflights13")
install.packages("hflights")
...
install.packages("devtools")
````

(I would suspect 'devtools' in your script didn't finish, and so 'dplyr' was skipped)

**Comment by rgbkrk** [comment]
Yeah I need devtools to use `install_github`. I'm surprised R doesn't error out for me during installs.

**Comment by stonebig** [comment]
maybe `devtools' is just so special that the R developper suppose they must `exit` at the end of installation as you must re-enter R to complete installation, or something like that.

Installing packages one by one should avoid these type of problems, I hope.

**Pull request merged**
