### PR TITLE
Added user target in Makefile

### PR DESCRIPTION
**Pull request by captainsafia**
I figured this might be helpful as a real quick start for users who just want to get up and running with tmpnb and aren't concerned about what's under the hood. It would also be useful when debugging with users so we know exactly what they ran on their machine.

cc: @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
The reason we weren't using the Makefile in the README was because the instructions were geared toward running this without having to clone the repo.

**Comment by rgbkrk** [comment]
Rather, that the intro doesn't use the Makefile. How they choose to orchestrate is up to them.

**Comment by captainsafia** [comment]
BROKE THE BUILD.

But makes sense. Closing...

**Comment by rgbkrk** [comment]
The build will remain broken until we have a `.travis.yml`. :wink:

**Pull request closed without merging**
