### PR TITLE
enable using tokens

### LINKED ISSUE #256: token authentication
Since Notebook 4.3 token authentication is on by default, and my tmpnb installation started asking for password. I eventually figured out I could set `--NotebookApp.token=""`, but I'm not sure if that is safe or if there is a recommended way. (I guess it is as safe as it was before since token authentication was disabled by default before. Or do I have that wrong?). 

I saw https://github.com/jupyter/tmpnb/issues/255 which seems related. Should I be using https://github.com/yuvipanda/jupyterhub-tmpauthenticator?

### PR DESCRIPTION
**Pull request by minrk**
off by default, but with `--use_tokens=1`, each user is assigned a token.

- [x] I need to get the tests working to verify that this works before merging.

closes #256

### CODE REVIEW

**Comment by minrk** [comment]
Tested and works.

**Comment by rgbkrk** [comment]
Nice! You'll need to rebase since I merged the networks PR.

**Comment by minrk** [comment]
@rgbkrk thanks, rebased and added the token to `/api/spawn`, which I had forgotten about.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
